# Generated by Django 4.1.4 on 2023-01-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_wings_wing_finch_wings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='breed',
            new_name='color',
        ),
    ]
